#!/bin/sh
#SBATCH -A asmith87
#SBATCH -n 1
#SBATCH --output=job.%J.out
#SBATCH --error=job.%J.err
#SBATCH --mem-per-cpu=8000

# How to run: sbatch slurmGurobi tdindp 2 2 8
# For a td-INDP run with 2 layers, 2 resources, and magnitude 8
ALGORITHM=$1
LAYERS=$2
RESOURCES=$3
MAGNITUDE=$4
FLIP=$5

GUROBI_HOME=/opt/gurobi650/linux64
PATH=${PATH}:${GUROBI_HOME}/bin
LD_LIBRARY_PATH=${GUROBI_HOME}/lib/

echo Algorithm: ${ALGORITHM}
echo Layers:    ${LAYERS}
echo Resources: ${RESOURCES}
echo Magnitude: ${MAGNITUDE}
echo Flip:      ${FLIP}

echo ${PYTHONPATH}

#srun `LD_LIBRARY_PATH=${LD_LIBRARY_PATH} PATH=${PATH} PYTHONPATH=${PYTHONPATH} python indpexp.py ${ALGORITHM} ${LAYERS} ${RESOURCES} ${MAGNITUDE} ${FLIP} > ${ALGORITHM}_${LAYERS}_${RESOURCES}_${MAGNITUDE}_${FLIP}.out 2> ${ALGORITHM}_${LAYERS}_${RESOURCES}_${MAGNITUDE}.err`
srun `LD_LIBRARY_PATH=${LD_LIBRARY_PATH} PATH=${PATH} PYTHONPATH=${PYTHONPATH} python indpexp.py > perc.out 2> perc.err`
